from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
ICON_PATH = FILES_DIR / 'icon.png'

#Sizing

BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
MINIMUM_WIDTH = 500
TEXT_MARGIN = 10

#Color

PRIMARY_COLOR = '#0066cc'
DARKER_PRIMARY_COLOR = '#00478f' 
DARKEST_PRIMARY_COLOR = '#002952'